pipeline:
  identifier: Build_spring_petclinic_1698127095647
  name: Build spring-petclinic
  orgIdentifier: default
  projectIdentifier: test_build
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698124933093
        repoName: spring-petclinic
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
